CREATE TABLE IF NOT EXISTS activity_status (id VARCHAR(80) PRIMARY KEY, available BOOLEAN NOT NULL, updated_at VARCHAR(80) NOT NULL);
CREATE TABLE IF NOT EXISTS trips (id VARCHAR(80) PRIMARY KEY, preferences TEXT NOT NULL, plan TEXT NOT NULL, revision INTEGER NOT NULL DEFAULT 1);
