CREATE TABLE IF NOT EXISTS activity_status (id VARCHAR(80) PRIMARY KEY, available BOOLEAN NOT NULL, updated_at VARCHAR(80) NOT NULL);
CREATE TABLE IF NOT EXISTS trips (id VARCHAR(80) PRIMARY KEY, preferences TEXT NOT NULL, plan TEXT NOT NULL, revision INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS problem_reports (id VARCHAR(80) PRIMARY KEY, category VARCHAR(40) NOT NULL, location VARCHAR(200) NOT NULL, description TEXT NOT NULL, created_at VARCHAR(80) NOT NULL);
